# Generated by Django 5.0.4 on 2024-05-01 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
